### ISSUE TITLE
[Bug] Duplicate languages

### ISSUE THREAD

**Issue by shapoval-darya** [ilyalehchylin/educats-xamarin#118]
On the first entry languages display correct
https://user-images.githubusercontent.com/55026109/79591567-6218a280-80e1-11ea-95ed-221c5b041127.jpg

but on the second - duplicate
https://user-images.githubusercontent.com/55026109/79591564-60e77580-80e1-11ea-9c3b-d83f8b67b194.jpg)

**Comment by ilyalehchylin** [comment]
Thanks, should be fixed with the next update.
